Set tsconfig to strictest #1445
sinProject-Inc/talk pull request #1446
Opened 2023-10-31 08:53 UTC by REI-MORI

closes #1445

# For the Submitter

## Tasks

- [ ] Make sure all checkboxes in the Issue content are checked
- [ ] Make sure the PR title is in the format `<Issue Title> <Issue Number>`
- [ ] Make sure "closes (issue number)" is written close to the top
- [ ] Attach the enhancement label for update tasks
- [ ] Make sure CI completes successfully
- [ ] Check everything written in the PR
- [ ] Fix the issues pointed out by AI
- [ ] Add reviewers
- [ ] On Slack, mention the PR reviewer, write your thoughts on the issue, and inform them that the PR has been created

# For the Reviewer

## Checks

- [ ] Each task for the related issue are written and in checkboxes
- [ ] The branch name is close to the issue name
- [ ] CI completes successfully
- [ ] Changes include only what is necessary for this PR
- [ ] Necessary unit tests are implemented
- [ ] Necessary E2E tests are implemented
- [ ] Perform functionality checks
- [ ] If there are any problems, request revisions from the PR submitter and mention them on Slack

## After Reviewing

- [ ] Leave an approval comment (e.g. LGTM)
- [ ] On Slack, mention the PR submitter and a project admin, write which PR you have reviewed, and ask them to merge the PR
- [ ] Write an approval comment with praise on Slack

2023-11-11 09:13 UTC, Acha0203 reviewed
2 点コメントしましたのでご確認をお願いいたします。

2023-11-11 09:13 UTC, Acha0203 commented on src/lib/translation/translate_with_google_advanced.ts
> +			if (!response.translations || !response.translations[0]) return ''
この行が sonarcloud の Code Smells として検出されていますので、修正していただけないでしょうか。

Message: Prefer using an optional chain expression instead, as it's more concise and easier to read.

2023-11-11 09:13 UTC, Acha0203 commented on src/routes/api/text-to-speech/[text=speech_text]/[locale_code=locale_code]/+server.ts
> +		if (!speech_sounds || !speech_sounds[0]) throw new Error('speech_sounds is undefined')
この行が sonarcloud の Code Smells として検出されていますので、修正していただけないでしょうか。

Message: Prefer using an optional chain expression instead, as it's more concise and easier to read.

2023-11-11 09:30 UTC, Acha0203 submitted a review, later dismissed
LGTM

2023-11-13 09:09 UTC, sinproject-iwasaki requested changes
@Acha0203 @REI-MORI 

PRへ送る方、レビューする方も、SonarCloud の報告を正しく確認して修正してください。

- [ ] SonarCloud で Smell が2件報告されているので修正する。
- [ ] SonarCloud で Duplication が報告されているので修正する。この場合は、test.each() の実装に変更する。（他のプロジェクトを参考にしてください。）

2023-11-13 09:20 UTC, sinproject-iwasaki requested changes
- [ ] テストケースはすべて、同じ関数や処理の流れに対して複数のテストケースを流す場合は、test.each (Vitestでは今後正しくは it.each() となります）を利用する。template-for-sveltekit や sinpro-dev のテストコードを参考にする。)

2023-11-13 09:20 UTC, sinproject-iwasaki commented on package.json
> +		"vite-plugin-pwa": "^0.16.6",
- [ ] 関係ないのであれば削除する。（strictest の関係ないのでは？）

2023-11-13 09:20 UTC, sinproject-iwasaki commented on src/lib/general/text_error.test.ts
> +import { expect, test } from 'vitest'
- [ ] 同じ関数に対するテストは, test.each() を使用する。（SonarCloud でも重複として指摘されます。他のプロジェクトを参考にしてください。）

2023-11-13 09:20 UTC, sinproject-iwasaki commented on src/lib/git/create_git_branch.ts
>  			throw new Error('Invalid issue string format')
- [ ] create_git_branch.ts ファイルと 同 test.ts ファイルは、sinpro-template-for-sveltekit からコピーして最新にする。（そういう対応であれば問題ありません。）

2023-11-13 09:20 UTC, sinproject-iwasaki commented on src/lib/text/valid_text.test.ts
> +import { expect, test } from 'vitest'
- [ ] こちらも、同じファンクションに対して違う値をテストする場合は、test.each() を利用する。

2023-11-13 09:20 UTC, sinproject-iwasaki commented on tsconfig.json
> +		"types": ["vite-plugin-pwa/info", "vitest/importMeta"]
- [ ] この Issue で vite-plugin-pwa/info が不要であれば削除する。

2023-11-13 10:32 UTC, REI-MORI commented on src/lib/git/create_git_branch.ts
>  			throw new Error('Invalid issue string format')
@sinproject-iwasaki  create_git_branch.tsのテストファイルはsinpro-template-for-sveltekit、他リポジトリにも存在しませんでしたので、create_git_branch.tsだけ最新化いたしました。

2023-11-13 12:15 UTC, Acha0203 reviewed
1件コメントしましたのでご確認をお願いいたします。

2023-11-13 12:15 UTC, Acha0203 commented on src/lib/network/client_hostname.test.ts
> +	const actual_dns = (await vi.importActual('dns')) as typeof import('dns')
この行が Code Smell として検出されています。

https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=CODE_SMELL&pullRequest=1446&id=sinProject-Inc_talk&open=AYvITbIT8RMuVILdOziR

2023-11-13 12:17 UTC, REI-MORI commented on src/lib/network/client_hostname.test.ts
> +	const actual_dns = (await vi.importActual('dns')) as typeof import('dns')
@Acha0203 こちらですが、フォーマッタにより保存時に強制的に変更させられてしまう部分となります。

2023-11-13 13:00 UTC, Acha0203 approved these changes
LGTM

2023-11-14 02:35 UTC, sinproject-iwasaki requested changes
@REI-MORI @Acha0203 

まだこちらはマージできないように思いました。個別に確認してみてくださいませ。

---

@REI-MORI 

- [ ] SonarCloud Actions でエラーが出ている。エラーを解消してからレビューを依頼する。
- [ ] 0.0% Coverage となっている。これは、https://github.com/sinProject-Inc/talk/pull/1460 をマージしてからでないとマージできないと思いますがいかがですか？
- [ ] テストコードの書き方が違っていたのでコードにコメントしました。ご確認ください。
- [ ] 次のレビュワーからのアドバイスがないように確認してからレビューやマージの依頼をする。
- [ ] レビューでの指摘があった場合、同じアドバイスを受けないようにアドバイスの内容をしっかり理解する。

---

@Acha0203 

- [ ] SonarCloud Actions でエラーが出ている。エラーを解消してからレビューを依頼する。
- [ ] 0.0% Coverage となっている。これは、https://github.com/sinProject-Inc/talk/pull/1460 をマージしてからでないとマージできないと思いますがいかがですか？
- [ ] テストコードの書き方が違っていたのでコードにコメントしました。ご確認ください。
- [ ] 次のレビュワーからのアドバイスがないように確認してからレビューやマージの依頼をする。
- [ ] レビューでの指摘があった場合、同じアドバイスを受けないようにアドバイスの内容をしっかり理解する。

2023-11-14 02:35 UTC, sinproject-iwasaki commented on src/lib/general/text_error.test.ts
> +import { TextError } from './text_error'
コード全体に対するレビューです。

- [ ] テストケースの書き方が違います。もう一度 https://sinpro.dev や、他のプロジェクトを確認する。
- [ ] テストケースの type を準備する。
- [ ] テストケースの命名を他のプロジェクトにそろえる。

2023-11-14 02:35 UTC, sinproject-iwasaki commented on src/lib/text/valid_text.test.ts
> +import { ValidText } from './valid_text'
- [ ] こちらのテストケースもほかのテストケースと同じ対応を行う。

2023-11-14 02:35 UTC, sinproject-iwasaki commented on src/lib/view/message.test.ts
> +// FILEPATH: /Users/morirei/Projects/talk/src/lib/view/message.test.ts
- [ ] 1行目のコメントは必要ですか？不要であれば消去する。
- [ ] 同様のテストは test.each にする。

2023-11-22 11:07 UTC, Acha0203 approved these changes
LGTM

2023-11-23 02:07 UTC, sinproject-iwasaki approved these changes
LGTM

2023-11-23 02:07 UTC, merged