#189 make translation and main locale same
sinProject-Inc/talk pull request #200
Opened 2023-02-03 05:24 UTC by milkyskies

2023-02-04 02:13 UTC, milkyskies commented
- [ ] History doesn't display on main page

2023-02-04 05:28 UTC, sinproject-iwasaki requested changes
最新の main を取得した上、コンフリクトを解消してください。

2023-02-05 09:18 UTC, milkyskies commented
- [ ] Switch languages on translate
- [ ] Fix app locale settings
- [ ] Delete text when changing locale
- [ ] Fix audio not playing

2023-02-05 10:20 UTC, sinproject-iwasaki commented on src/lib/api/api_path.ts
> +	public connect_with_params(params: Record<string, string>): ApiPath {
get_url の上に移動する。

2023-02-05 10:20 UTC, sinproject-iwasaki commented on src/lib/auth/email.test.ts
> +})
Prettier で format してみてください。

2023-02-05 10:23 UTC, sinproject-iwasaki commented on src/lib/components/text_list_text.svelte
> +	export let delete_text: (text: Text) => void = () => {
format かけたらこうなる？

2023-02-05 10:23 UTC, sinproject-iwasaki commented on src/lib/components/text_list_text.svelte
> +	export let delete_text: (text: Text) => void = () => {
一回一行にしてみて、その後 Prettier でフォーマットかけて試してみてください。

2023-02-05 10:31 UTC, sinproject-iwasaki commented on src/lib/components/translate/translate_box.svelte
> +		audio_element.load()
play に戻してエラーを見てみたいです。

2023-02-05 10:51 UTC, sinproject-iwasaki commented on src/lib/text/text_db.ts
> +
delete blank line

2023-02-05 10:56 UTC, sinproject-iwasaki commented on src/lib/text/texts_api.test.ts
> +const origin = 'http://localhost:5173'
App に localhost_origin を作成する。

2023-02-05 10:57 UTC, sinproject-iwasaki commented on src/lib/text/texts_api.ts
> +		this._api_path = ApiPath.api_directory.connect('text').connect(speech_language_code.code).connect_with_params({ limit: limit?.toString() ?? '' })
format

2023-02-05 10:58 UTC, sinproject-iwasaki commented on src/lib/text/texts_api.ts
> +		this._api_path = ApiPath.api_directory.connect('text').connect(speech_language_code.code).connect_with_params({ limit: limit?.toString() ?? '' })
connect_with_params() メソッドで、null | undefined の判定を行う

2023-02-05 11:00 UTC, sinproject-iwasaki commented on src/routes/+page.svelte
> +
remove blank line

2023-02-05 11:01 UTC, sinproject-iwasaki commented on src/routes/api/text/[language_code]/+server.ts
> +import type { Text } from '@prisma/client'
使ってない？

2023-02-05 11:15 UTC, sinproject-iwasaki commented on src/routes/translate/+page.svelte
> +
remove blank line

2023-02-05 11:38 UTC, sinproject-iwasaki commented on src/routes/+page.svelte
remove blank line

2023-02-05 11:48 UTC, sinproject-iwasaki commented on src/routes/+page.svelte
> +
remove blank line

2023-02-05 12:20 UTC, sinproject-iwasaki commented on src/lib/components/translate/translate_box.svelte
> +	import { TextToSpeechUrl } from '$lib/speech/text_to_speech_url'
remove

2023-02-05 12:38 UTC, sinproject-iwasaki requested changes
- [x] Translate マイクが動作しない。

2023-02-05 13:01 UTC, sinproject-iwasaki approved these changes
LGTM

2023-02-05 13:02 UTC, merged