translate: Limit to 250 characters #258
sinProject-Inc/talk pull request #280
Opened 2023-02-08 07:23 UTC by milkyskies

closes #258

2023-02-08 07:50 UTC, sinproject-iwasaki requested changes
- [x] 250文字の日本語から英語への翻訳をするテストを記載する。
- [x] 251文字の日本語から英語への翻訳をするテストを記載する。
- [x] 250文字の日本語から英語へ翻訳して、エラーが出ないように対応する。

2023-02-08 08:14 UTC, sinproject-iwasaki commented
- [ ] 上記レビュー内容を確認して、対応したらチェックをしてください。
- [ ] varchar と nvarchar の違いを確認した上で、nvarchar に変更してください。

2023-02-08 13:00 UTC, sinproject-iwasaki requested changes
- [ ] 250文字以上で翻訳をかけると、以前の翻訳が再生される。

2023-02-08 13:00 UTC, sinproject-iwasaki commented on src/lib/general/text_error.ts
> +export class TextError extends Error {
継承をやめる。

2023-02-08 13:00 UTC, sinproject-iwasaki commented on src/lib/components/translate/translate_box.svelte
> +
Remove blank line

2023-02-08 13:00 UTC, sinproject-iwasaki commented on src/lib/text/base_text.ts
> +  text: string
get text(): string

2023-02-08 13:10 UTC, milkyskies commented
@sinproject-iwasaki 修正を行いました。

2023-02-09 04:02 UTC, sinproject-iwasaki requested changes

2023-02-09 04:29 UTC, sinproject-iwasaki approved these changes

2023-02-09 04:30 UTC, sinproject-iwasaki requested changes
- [ ] コンフリクトを解消してください。

2023-02-09 05:05 UTC, milkyskies commented
- [ ] Bug when original text is shorter than 250 chars but translated text is more than 250

2023-02-09 05:41 UTC, sinproject-iwasaki approved these changes
LGTM

2023-02-09 05:41 UTC, sinproject-iwasaki approved these changes
LGTM

2023-02-09 05:42 UTC, merged