Don't call fetch API when clicking on a text in the history  #284
sinProject-Inc/talk pull request #285
Opened 2023-02-08 07:42 UTC by milkyskies

closes #284

2023-02-08 08:06 UTC, sinproject-iwasaki commented on src/lib/components/translate/translate_box.svelte
> +		if (refresh_history) {
- [ ] User "Early Return"

2023-02-08 08:06 UTC, sinproject-iwasaki requested changes
コード内コメントを確認してください。

2023-02-08 13:16 UTC, milkyskies commented
@sinproject-iwasaki 修正を行いました。

2023-02-09 04:10 UTC, sinproject-iwasaki approved these changes

2023-02-09 04:10 UTC, merged