translate: support arabic UI #417
sinProject-Inc/talk pull request #421
Opened 2023-03-19 05:03 UTC by milkyskies

closes #417

2023-03-19 06:41 UTC, sinproject-iwasaki requested changes
次回からは、依頼された詳細項目を Issue に記載して、対応漏れがないようにしてください。

- [x] バツボタンの位置を調整する。
- [x] アイコンの位置を調整する。
- [ ] NG 履歴テキストの位置を調整する。

2023-03-20 09:32 UTC, sinproject-iwasaki commented
- [ ] バツボタンとテキストが重ならないようにする。

<img width="814" alt="Screenshot 2023-03-20 at 18 28 57" src="https://user-images.githubusercontent.com/70736447/226299818-d14bf819-22d6-4d8b-a700-d11013aa80a4.png">

- [ ] アラビア語モードのとき、ボタンの位置を左にする。
<img width="800" alt="Screenshot 2023-03-20 at 18 30 25" src="https://user-images.githubusercontent.com/70736447/226299835-da45ed71-7ce6-43e2-aa55-df27440788ea.png">

2023-03-21 02:16 UTC, sinproject-iwasaki commented
- [ ] 入力欄の言語がアラビア語でない場合は、テキストを左から表示する。（この場合、上部は日本語）

![Screenshot 2023-03-21 at 11 12 17](https://user-images.githubusercontent.com/70736447/226503450-fe17c175-1fd6-4598-a5e4-0bb12170482b.png)

- [ ] 入力欄の言語がアラビアの場合、テキストを右から表示する。（この場合、上部はアラビア語）

![Screenshot 2023-03-21 at 11 14 02](https://user-images.githubusercontent.com/70736447/226503645-45c78852-f198-4ac0-9588-0e61c744ae11.png)

- [ ] メイン画面履歴：アラビア語の場合、右からテキストを表示する。

![Screenshot 2023-03-21 at 11 10 28](https://user-images.githubusercontent.com/70736447/226503285-edd91353-930f-470d-a0e1-88e84679f4c4.png)

2023-03-23 06:05 UTC, sinproject-iwasaki commented
PRで何度もリジェクトになるとマージまでに時間を費やしてしまいまい、お互い辛くなってきます。
新たな指摘をされないように品質に意識して、UIや動作のチェックをしっかり行っていきましょう。

- [ ] アラビア語表示の際、上記の他言語のテキストの左（「そちらの」の左）に余分なスペースが生じないようにする。

![Screenshot 2023-03-23 at 14 58 48](https://user-images.githubusercontent.com/70736447/227116947-fbdb4481-cbe4-4ac5-86a3-f5dabc5f6524.png)

- [ ] 日本語表示の際、上記がアラビア語でも、テキストの右に余分なスペースが生じないようにする。

![Screenshot 2023-03-23 at 14 59 10](https://user-images.githubusercontent.com/70736447/227117490-b340e079-4491-44bb-9665-ffec0f300513.png)

2023-03-27 09:23 UTC, milkyskies commented
- [ ] ボタンを入力言語の方向に合わせる

2023-03-31 10:56 UTC, sinproject-iwasaki approved these changes
LGTM

2023-03-31 10:56 UTC, merged