Decrease glass transparency #594
sinProject-Inc/talk pull request #944
Opened 2023-05-25 06:06 UTC by sakata0411

closes #594 

# For the Submitter

## Tasks

- [ ] Make sure "closes (issue number)" is written close to the top
- [ ] Add reviewers
- [ ] Make sure CI completes successfully
- [ ] On Slack, mention the PR reviewer, write your thoughts on the issue, and inform them that the PR has been created

# For the Reviewer

## Before Reviewing

- [ ] Write which PR you are reviewing on Slack

## Checks

- [ ] Each task for the related issue are written and in checkboxes
- [ ] The branch name is close to the issue name
- [ ] CI completes successfully
- [ ] Changes include only what is necessary for this PR
- [ ] Necessary unit tests are implemented
- [ ] Necessary E2E tests are implemented
- [ ] Perform functionality checks
- [ ] If there are any problems, request revisions from the PR submitter and mention them on Slack

## After Reviewing

- [ ] Leave an approval comment (e.g. LGTM)
- [ ] On Slack, mention the PR submitter and a project admin, write which PR you have reviewed, and ask them to merge the PR

2023-05-25 08:30 UTC, sinproject-iwasaki requested changes
- どれぐらいの透明度にする、どこの透明度に合わせるなどという詳細な指示はありましたか？
- もし上記指示がなく、漠然と対応してたとしてたらそれは多分NGとなりそうです。

(Docs で、コンテナ部分（コードブロック）の border, background, text-color などを独自に作成しているので、それにスタイルを合わせてほしいという意味合いで作成された Issue かと考えております。）

2023-05-26 05:22 UTC, milkyskies approved these changes

2023-05-26 05:28 UTC, milkyskies requested changes
文字のテキストも、コードブロックに合わせましたか？

2023-05-26 05:28 UTC, milkyskies requested changes
文字のテキストも、コードブロックに合わせましたか？

2023-05-26 06:11 UTC, sakata0411 commented
岩崎さんから頂いた指示の中に文字色については含まれていなかったため確認を行っていませんでした。
必要であれば再度確認を行いますがどうすべきでしょうか？

2023-05-28 12:34 UTC, milkyskies approved these changes
透明度を下げるというイシューだったので、マージします。
LGTM

2023-05-28 12:34 UTC, milkyskies approved these changes
透明度を下げるというイシューだったので、マージします。
LGTM

2023-05-28 12:34 UTC, merged